language: node_js

branches:
  only:
    - master

node_js:
  - 10

sudo: required

services:
  - docker

install:
  - docker pull trzeci/emscripten:sdk-incoming-64bit
  - npm ci

script:
  - npm run lint
  - docker run --name emscripten -v $PWD:/src trzeci/emscripten:sdk-incoming-64bit emmake make wasm
  - npm run build

after_success:
  - npm run deploy

cache:
  npm: true
  directories:
    - .cache
    - node_modules

notifications:
  email: false
